"""Add Code Smasher usage columns

Revision ID: 00f9117e80aa
Revises: 9aca090240ab
Create Date: 2025-07-17 19:17:28.464316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f9117e80aa'
down_revision = '9aca090240ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cs_usage_reset_at', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cs_usage_reset_at')

    # ### end Alembic commands ###
