"""Add referral_code to users

Revision ID: 05594be345fd
Revises: 00f9117e80aa
Create Date: 2025-07-21 04:52:21.893168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05594be345fd'
down_revision = '00f9117e80aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=10), nullable=False))
        batch_op.create_unique_constraint(None, ['referral_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('referral_code')

    # ### end Alembic commands ###
