"""Rename verified to is_verified

Revision ID: 0a4ce4f0a7ca
Revises: d3350a9433e4
Create Date: 2025-06-10 00:34:50.570286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4ce4f0a7ca'
down_revision = 'd3350a9433e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.drop_column('verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
