"""add encrypted_password to UserMemoryItem

Revision ID: 172b0a029167
Revises: 3d7cb1280af7
Create Date: 2025-07-11 00:04:39.381742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172b0a029167'
down_revision = '3d7cb1280af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_memory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_password', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_memory_items', schema=None) as batch_op:
        batch_op.drop_column('encrypted_password')

    # ### end Alembic commands ###
