"""Add referral_code_used to User

Revision ID: 2ce57e710b42
Revises: 8fdfaab1609f
Create Date: 2025-07-22 05:36:02.149537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce57e710b42'
down_revision = '8fdfaab1609f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code_used', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('referral_code_used')

    # ### end Alembic commands ###
