"""add pending_messages to User

Revision ID: 37ad496a6e2e
Revises: ce99c10ea7ca
Create Date: 2025-07-12 02:11:25.967387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ad496a6e2e'
down_revision = 'ce99c10ea7ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_messages', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pending_messages')

    # ### end Alembic commands ###
