"""create user_memory_items

Revision ID: 3d7cb1280af7
Revises: b9cd31f2324a
Create Date: 2025-07-10 22:38:37.730222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7cb1280af7'
down_revision = 'b9cd31f2324a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_column('is_lite')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_lite', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
