"""Remove học hành fields

Revision ID: 4445e6d1df6c
Revises: 0e0391bf6eaa
Create Date: 2025-06-12 21:35:49.610715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4445e6d1df6c'
down_revision = '0e0391bf6eaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('solves')
        batch_op.drop_column('vip_until_solver_edu')
        batch_op.drop_column('ads_used_today')
        batch_op.drop_column('last_solve_date')
        batch_op.drop_column('vip_solver_edu')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vip_solver_edu', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_solve_date', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ads_used_today', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vip_until_solver_edu', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('solves', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
