"""add avatar_url to users

Revision ID: 47563a1d3ed3
Revises: e17d43a360d0
Create Date: 2025-06-09 19:51:06.511944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47563a1d3ed3'
down_revision = 'e17d43a360d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
