"""add free_gpt_uses to users

Revision ID: 5816ef22b56f
Revises: 47563a1d3ed3
Create Date: 2025-06-09 20:03:52.295975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5816ef22b56f'
down_revision = '47563a1d3ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('free_gpt_uses', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('free_gpt_uses')

    # ### end Alembic commands ###
