"""Add email_temp column to User

Revision ID: 6a9b7b848a54
Revises: 4445e6d1df6c
Create Date: 2025-06-16 23:35:15.241885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a9b7b848a54'
down_revision = '4445e6d1df6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_temp', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_temp')

    # ### end Alembic commands ###
