"""Add SmartDoc usage fields

Revision ID: 8311808c9f2f
Revises: de751b2bad92
Create Date: 2025-07-16 22:06:32.015546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8311808c9f2f'
down_revision = 'de751b2bad92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smartdoc_usage_today', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('smartdoc_last_used_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('smartdoc_last_used_date')
        batch_op.drop_column('smartdoc_usage_today')

    # ### end Alembic commands ###
