"""Add pending_messages and last_sent_at to User

Revision ID: 8995d14ab269
Revises: 37ad496a6e2e
Create Date: 2025-07-13 20:47:51.364642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8995d14ab269'
down_revision = '37ad496a6e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_sent_at')

    # ### end Alembic commands ###
