"""remove school column

Revision ID: 8d75db026fb3
Revises: f94c75de0e57
Create Date: 2025-06-17 00:16:38.423073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d75db026fb3'
down_revision = 'f94c75de0e57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('school')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
