"""add reward info columns

Revision ID: 8fdfaab1609f
Revises: 05594be345fd
Create Date: 2025-07-22 05:00:10.235631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fdfaab1609f'
down_revision = '05594be345fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reward_info')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward_fullname', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reward_bank', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reward_stk', sa.String(length=30), nullable=True))
        batch_op.create_unique_constraint(None, ['referral_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('reward_stk')
        batch_op.drop_column('reward_bank')
        batch_op.drop_column('reward_fullname')

    op.create_table('reward_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('account_number', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('reward_info_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('reward_info_pkey'))
    )
    # ### end Alembic commands ###
