"""Add Code Smasher usage counters

Revision ID: 9aca090240ab
Revises: 8311808c9f2f
Create Date: 2025-07-17 19:15:17.714505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aca090240ab'
down_revision = '8311808c9f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cs_flatline_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cs_mindtwist_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cs_hexlock_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cs_hexlock_count')
        batch_op.drop_column('cs_mindtwist_count')
        batch_op.drop_column('cs_flatline_count')

    # ### end Alembic commands ###
