"""Add title column to SmartDoc

Revision ID: a684afcf8813
Revises: 8995d14ab269
Create Date: 2025-07-15 20:11:16.397473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a684afcf8813'
down_revision = '8995d14ab269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smart_docs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smart_docs', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
