"""Add BlockedUserLog

Revision ID: b4f4a9d98b06
Revises: 
Create Date: 2025-06-30 19:05:21.231506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f4a9d98b06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_usage_stats')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_usage_stats',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('slv_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lite_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_usage_stats_pkey')),
    sa.UniqueConstraint('date', name=op.f('daily_usage_stats_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
