"""empty message

Revision ID: b92b8e286a9d
Revises: 174a8b09f769
Create Date: 2025-07-05 19:10:11.234923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92b8e286a9d'
down_revision = '174a8b09f769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocked_user_log', schema=None) as batch_op:
        batch_op.drop_column('email_sent')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_quota_today', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('image_quota_reset_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('image_quota_reset_at')
        batch_op.drop_column('image_quota_today')

    with op.batch_alter_table('blocked_user_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_sent', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
