"""Thêm cột is_lite cho ChatHistory

Revision ID: b9cd31f2324a
Revises: e38862c495f2
Create Date: 2025-07-08 18:50:00.543560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9cd31f2324a'
down_revision = 'e38862c495f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_lite', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_column('is_lite')

    # ### end Alembic commands ###
