"""Add updated_at to UserMemoryItem

Revision ID: ce99c10ea7ca
Revises: 172b0a029167
Create Date: 2025-07-11 00:35:46.141951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce99c10ea7ca'
down_revision = '172b0a029167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_memory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_memory_items', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
