"""add otp_code to users

Revision ID: d6dc0104b180
Revises: eb054db89194
Create Date: 2025-06-09 19:24:13.347319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6dc0104b180'
down_revision = 'eb054db89194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('online', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('online')
        batch_op.drop_column('otp_code')

    # ### end Alembic commands ###
