"""add author_name to smartdoc

Revision ID: de751b2bad92
Revises: a684afcf8813
Create Date: 2025-07-15 21:26:46.073331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de751b2bad92'
down_revision = 'a684afcf8813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smart_docs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smart_docs', schema=None) as batch_op:
        batch_op.drop_column('author_name')

    # ### end Alembic commands ###
