"""add wants_verification to users

Revision ID: e17d43a360d0
Revises: 8da2b17829f7
Create Date: 2025-06-09 19:41:02.590219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17d43a360d0'
down_revision = '8da2b17829f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wants_verification', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('wants_verification')

    # ### end Alembic commands ###
