"""empty message

Revision ID: e38862c495f2
Revises: b92b8e286a9d
Create Date: 2025-07-07 19:18:37.910600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e38862c495f2'
down_revision = 'b92b8e286a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_index', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_history', schema=None) as batch_op:
        batch_op.drop_column('message_index')

    # ### end Alembic commands ###
