"""remove messages column from User

Revision ID: fa174950d76b
Revises: 8d75db026fb3
Create Date: 2025-06-17 00:34:15.565577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa174950d76b'
down_revision = '8d75db026fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('messages')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('messages', postgresql.BYTEA(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
